name: Build and Deploy Docker Image to GHCR

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DATE_TAG: ${{ steps.set_date.outputs.date }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set current date
        id: set_date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.DATE_TAG }}